<?php

use Bitrix\Main\ModuleManager;
use Bitrix\Main\Localization\Loc;
use Bitrix\Main\Loader;
use My\AutoSelection\Helper;
use My\Autoselection\Migrations;
use Bitrix\Main;

Loc::loadMessages(__FILE__);
class my_autoselection extends CModule
{
//TODO https://dev.1c-bitrix.ru/learning/course/index.php?COURSE_ID=43&LESSON_ID=2823
    function __construct(
//        public bool $moduleCheck = true
    )
    {
        $arModuleVersion = array();
        include(dirname(__FILE__) . '/version.php');

        $this->MODULE_ID = 'my.autoselection';
        $this->MODULE_VERSION = $arModuleVersion['VERSION'];
        $this->MODULE_VERSION_DATE = $arModuleVersion['VERSION_DATE'];

        $this->MODULE_NAME = Loc::getMessage('MODULE_NAME');
        $this->MODULE_DESCRIPTION = Loc::getMessage('MODULE_DESCRIPTION');
        $this->PARTNER_NAME = Loc::getMessage('PARTNER_NAME');
        $this->PARTNER_URI = Loc::getMessage('PARTNER_URI');
        $this->arSiteList = ['s1'];

//        $this->moduleCheck = self::checkModules(); //TODO добавить функцию проверки модулей @return bool
    }

    function DoInstall()
    {
        global $APPLICATION;
        ModuleManager::registerModule($this->MODULE_ID); // TODO: Change the autogenerated stub
        $this->InstallHlBlock();
        $this->InstallIBlock();

    }
    function DoUninstall()
    {
        ModuleManager::unRegisterModule($this->MODULE_ID); // TODO: Change the autogenerated stub
    }

    function InstallIBlock()
    {
        Loader::includeModule($this->MODULE_ID);
        $obIBlock = new Migrations\Autoselection();
        $obIBlock->up();
    }

    function InstallHlBlock()
    {
        Loader::includeModule($this->MODULE_ID);
        $obHlBlock = new Migrations\Brands('s1');
        $obHlBlock->up();
    }

    function InstallEvents()
    {
        $eventManager = Main\EventManager::getInstance();
        /**Установка события для добавления кнопки меню*/
        $eventManager->registerEventHandler(
            'main',
            'OnPageStart',
            $this->MODULE_ID,
            'Me\AutoSelection\Handlers\BuildOnBeforeProlog',
            'bootstrapOn'
        );
        $eventManager->registerEventHandler(
            'main',
            'OnEpilog',
            $this->MODULE_ID,
            'Me\AutoSelection\Handlers\BuildOnBeforeEpilog',
            'addHeaderButton');
    }
}